# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buffy.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("buffy.proto", :syntax => :proto2) do
    add_message "Buffy" do
      required :thing, :string, 1
    end
  end
end

Buffy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Buffy").msgclass
